#!/usr/bin/env python3
"""Generate a mathematical presentation PDF for void-theory results."""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak,
    Table, TableStyle, HRFlowable
)
from reportlab.lib.colors import black, HexColor
from reportlab.lib.units import mm, cm

output_path = "/sessions/laughing-hopeful-bohr/mnt/void-theory/void_theorem.pdf"

doc = SimpleDocTemplate(
    output_path,
    pagesize=A4,
    topMargin=2.5*cm,
    bottomMargin=2.5*cm,
    leftMargin=2.8*cm,
    rightMargin=2.8*cm,
)

styles = getSampleStyleSheet()

# Custom styles
title_style = ParagraphStyle(
    'CustomTitle',
    parent=styles['Title'],
    fontSize=18,
    spaceAfter=6,
    leading=22,
    alignment=TA_CENTER,
)

subtitle_style = ParagraphStyle(
    'Subtitle',
    parent=styles['Normal'],
    fontSize=11,
    spaceAfter=20,
    leading=14,
    alignment=TA_CENTER,
    textColor=HexColor('#444444'),
)

section_style = ParagraphStyle(
    'Section',
    parent=styles['Heading2'],
    fontSize=13,
    spaceBefore=18,
    spaceAfter=8,
    leading=16,
    fontName='Times-Bold',
)

body_style = ParagraphStyle(
    'Body',
    parent=styles['Normal'],
    fontSize=11,
    leading=15,
    alignment=TA_JUSTIFY,
    fontName='Times-Roman',
    spaceAfter=6,
)

definition_style = ParagraphStyle(
    'Definition',
    parent=body_style,
    leftIndent=12,
    rightIndent=12,
    spaceBefore=8,
    spaceAfter=8,
    fontName='Times-Roman',
)

theorem_style = ParagraphStyle(
    'Theorem',
    parent=body_style,
    leftIndent=12,
    rightIndent=12,
    spaceBefore=10,
    spaceAfter=10,
    fontName='Times-BoldItalic',
)

proof_style = ParagraphStyle(
    'Proof',
    parent=body_style,
    leftIndent=12,
    rightIndent=12,
    fontName='Times-Italic',
    spaceAfter=8,
)

remark_style = ParagraphStyle(
    'Remark',
    parent=body_style,
    leftIndent=12,
    rightIndent=12,
    spaceBefore=6,
    spaceAfter=6,
)

small_style = ParagraphStyle(
    'Small',
    parent=body_style,
    fontSize=9,
    leading=12,
    alignment=TA_CENTER,
    textColor=HexColor('#666666'),
)

story = []

# --- TITLE ---
story.append(Paragraph(
    "Bayesian Inference on Finite Fractions<br/>Without Countable Additivity",
    title_style
))
story.append(Paragraph(
    "A Machine-Verified Result in Coq",
    subtitle_style
))
story.append(HRFlowable(width="60%", thickness=0.5, color=HexColor('#999999'),
                          spaceAfter=12, spaceBefore=0))
story.append(Paragraph(
    "VOID Project &nbsp;&nbsp;|&nbsp;&nbsp; March 2026",
    small_style
))
story.append(Spacer(1, 16))

# --- 1. SETTING ---
story.append(Paragraph("1. Setting", section_style))

story.append(Paragraph(
    "Let <b>Fin</b> denote the type of unary natural numbers, "
    "generated by a zero constructor <i>fz</i> and a successor <i>fs</i>. "
    "We write elements as 0, 1, 2, ... with the understanding that each numeral "
    "abbreviates a chain of successors. All arithmetic on <b>Fin</b> is "
    "structurally recursive and total. There are no partial functions, "
    "no limits, and no infinite objects.",
    body_style
))

story.append(Paragraph(
    "We equip <b>Fin</b> with a structural ordering:",
    body_style
))

story.append(Paragraph(
    "<b>Definition.</b>&nbsp; "
    "The relation <i>n</i> &le; <i>m</i> (written <i>leF n m</i>) is "
    "the smallest relation satisfying: &nbsp;"
    "(i) 0 &le; <i>m</i> for all <i>m</i>, and &nbsp;"
    "(ii) if <i>n</i> &le; <i>m</i> then <i>n</i>+1 &le; <i>m</i>+1.",
    definition_style
))

story.append(Paragraph(
    "This is a decidable total order on <b>Fin</b> (proven in Coq: "
    "<i>leF_or_gt, leF_antisym, leF_trans</i>).",
    body_style
))

# --- 2. FROZEN DENOMINATOR ---
story.append(Paragraph("2. The Frozen Denominator Model", section_style))

story.append(Paragraph(
    "<b>Definition.</b>&nbsp; "
    "A <i>frozen probability</i> is a pair (<i>p</i>, <i>D</i>) "
    "where <i>p</i>, <i>D</i> &isin; <b>Fin</b> and <i>p</i> &le; <i>D</i>. "
    "We interpret this as the rational number <i>p</i>/<i>D</i>. "
    "The denominator <i>D</i> is fixed throughout computation; "
    "only the numerator <i>p</i> changes.",
    definition_style
))

story.append(Paragraph(
    "Given a prior (<i>p</i>, <i>D</i>), a likelihood <i>L</i>, and a "
    "counter-likelihood <i>C</i>, we define two update operations:",
    body_style
))

story.append(Paragraph(
    "<b>Definition (Exact update).</b>&nbsp; "
    "Compute the standard Bayesian posterior numerator: "
    "<i>p</i>' = (<i>p</i> &middot; <i>L</i>) / "
    "(<i>p</i> &middot; <i>L</i> + (<i>D</i> &minus; <i>p</i>) &middot; <i>C</i>), "
    "scaled to denominator <i>D</i>. This requires multiplication and division on <b>Fin</b>.",
    definition_style
))

story.append(Paragraph(
    "<b>Definition (Additive update).</b>&nbsp; "
    "Determine whether the evidence supports or refutes the hypothesis "
    "(by comparing <i>L</i> to <i>C</i>). Then:",
    definition_style
))

story.append(Paragraph(
    "&nbsp;&nbsp;&nbsp;&nbsp;If <i>supporting</i>: &nbsp; "
    "<i>p</i><sub>add</sub> = min(<i>p</i>', <i>D</i> &minus; 1). <br/>"
    "&nbsp;&nbsp;&nbsp;&nbsp;If <i>refuting</i>: &nbsp;&nbsp;&nbsp; "
    "<i>p</i><sub>add</sub> = max(<i>p</i>', 1).",
    definition_style
))

story.append(Paragraph(
    "The capping at <i>D</i> &minus; 1 and flooring at 1 enforce an invariant: "
    "the system never reaches absolute certainty (0 or <i>D</i>). "
    "When evidence is neutral or computational resources are exhausted, "
    "the system returns a distinguished value <i>Unknown</i> "
    "instead of producing a spurious posterior.",
    body_style
))

# --- 3. MAIN THEOREM ---
story.append(Paragraph("3. Main Theorem", section_style))

story.append(Paragraph(
    "<b>Theorem</b> (bayes_additive_bounded_error, Coq: <i>Qed</i>)<b>.</b>&nbsp; "
    "Let (<i>p</i>, <i>D</i>) be a frozen probability, and let <i>L</i>, <i>C</i> be "
    "likelihood and counter-likelihood. Under the hypothesis that computational resources "
    "suffice (the <i>sufficient_budget</i> predicate), the additive update and "
    "the exact Bayesian update satisfy:",
    theorem_style
))

story.append(Paragraph(
    "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
    "| <i>p</i><sub>add</sub> &minus; <i>p</i>' | &nbsp; &le; &nbsp; 1",
    ParagraphStyle('CenterMath', parent=body_style, alignment=TA_CENTER,
                   fontSize=14, spaceBefore=8, spaceAfter=8, fontName='Times-BoldItalic')
))

story.append(Paragraph(
    "where the distance is measured in numerator steps (units of 1/<i>D</i>).",
    body_style
))

story.append(Paragraph(
    "<b>Proof structure.</b>&nbsp; "
    "The proof proceeds by case analysis on the evidence direction. "
    "Two auxiliary lemmas provide the core bounds:",
    body_style
))

story.append(Paragraph(
    "<i>Lemma</i> (pure_capped_error_bound). "
    "For all <i>n</i>, <i>D</i>' &isin; <b>Fin</b>: "
    "if <i>n</i> &le; <i>D</i>'+1, then "
    "<i>n</i> &minus; min(<i>n</i>, <i>D</i>') &le; 1.",
    definition_style
))

story.append(Paragraph(
    "<i>Lemma</i> (pure_floored_error_bound). "
    "For all <i>n</i> &isin; <b>Fin</b>: "
    "max(<i>n</i>, 1) &minus; <i>n</i> &le; 1.",
    definition_style
))

story.append(Paragraph(
    "Both lemmas are proven by structural induction on <b>Fin</b>. "
    "The main theorem connects the budgeted (computational) operations "
    "to these pure arithmetic facts via bridge lemmas, and closes the "
    "neutral case by contradiction. "
    "The full proof is machine-verified: zero admitted lemmas.",
    body_style
))

# --- 4. FINITE ADDITIVITY ---
story.append(Paragraph("4. Finite Additivity", section_style))

story.append(Paragraph(
    "The arithmetic of frozen probabilities satisfies:",
    body_style
))

story.append(Paragraph(
    "<i>Lemma</i> (fin_add_comm). "
    "For all <i>a</i>, <i>b</i> &isin; <b>Fin</b>: &nbsp;"
    "<i>a</i> + <i>b</i> = <i>b</i> + <i>a</i>. <br/>"
    "<i>Lemma</i> (fin_add_assoc). "
    "For all <i>a</i>, <i>b</i>, <i>c</i> &isin; <b>Fin</b>: &nbsp;"
    "<i>a</i> + (<i>b</i> + <i>c</i>) = (<i>a</i> + <i>b</i>) + <i>c</i>.",
    definition_style
))

story.append(Paragraph(
    "Together with the ordering lemmas (absorption laws, idempotency), "
    "these establish that <b>Fin</b> supports a well-behaved finite additive structure. "
    "Crucially, no infinite sum operation is definable on <b>Fin</b>, "
    "since every element is bounded by a fixed maximum (<i>fin_bounded</i> axiom).",
    body_style
))

# --- 5. KOLMOGOROV ---
story.append(Paragraph("5. Relation to Kolmogorov's Axioms", section_style))

story.append(Paragraph(
    "Kolmogorov's axiomatization of probability (1933) rests on six conditions. "
    "The sixth and strongest is <i>countable additivity</i>: "
    "for any countable sequence of pairwise disjoint events "
    "<i>A</i><sub>1</sub>, <i>A</i><sub>2</sub>, <i>A</i><sub>3</sub>, ..., ",
    body_style
))

story.append(Paragraph(
    "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
    "P(&cup;<sub><i>i</i>=1</sub><super>&infin;</super> <i>A<sub>i</sub></i>) "
    "&nbsp;=&nbsp; "
    "&Sigma;<sub><i>i</i>=1</sub><super>&infin;</super> P(<i>A<sub>i</sub></i>)",
    ParagraphStyle('CenterMath2', parent=body_style, alignment=TA_CENTER,
                   fontSize=13, spaceBefore=8, spaceAfter=8, fontName='Times-Roman')
))

story.append(Paragraph(
    "This axiom is the point at which infinity enters the foundations of probability theory. "
    "It requires the existence of countably infinite partitions and an infinite summation "
    "operation. The third axiom (the &sigma;-algebra) provides the structural support "
    "for this, requiring closure under countable unions.",
    body_style
))

story.append(Paragraph(
    "In the frozen denominator system, the event space for denominator <i>D</i> is "
    "the finite set {0/<i>D</i>, 1/<i>D</i>, ..., <i>D</i>/<i>D</i>}, "
    "containing at most <i>D</i>+1 elements. Every subset is trivially measurable. "
    "No &sigma;-algebra is needed. Countable additivity is not merely unnecessary "
    "but <i>inexpressible</i>: the type <b>Fin</b> admits no infinite sequences, "
    "no infinite sums, and no limits.",
    body_style
))

story.append(Paragraph(
    "<b>Observation.</b>&nbsp; "
    "The theorem <i>bayesian_inference_without_axiom_6</i> (Coq: <i>Qed</i>) "
    "has identical content to <i>bayes_additive_bounded_error</i>. "
    "Its proof invokes no axiom of countable additivity, "
    "no &sigma;-algebra, no countable sum, and no limit. "
    "It uses only: <b>Fin</b> arithmetic, the <i>leF</i> ordering, "
    "and structural induction.",
    definition_style
))

# --- 6. INTERPRETATION ---
story.append(Paragraph("6. Interpretation", section_style))

story.append(Paragraph(
    "The result can be read as follows. Fix a resolution parameter <i>D</i> &isin; "
    "<b>Fin</b>. Within the finite probability space of denominator <i>D</i>, "
    "Bayesian updating is realizable by purely additive operations (no multiplication "
    "or division needed), with a worst-case error of 1/<i>D</i> per update step. "
    "Higher precision is obtained by choosing a larger <i>D</i> "
    "at the cost of increased computational budget.",
    body_style
))

story.append(Paragraph(
    "The system introduces three-valued logic (<i>BTrue</i>, <i>BFalse</i>, "
    "<i>BUnknown</i>) where the third value signals resource exhaustion or "
    "genuinely undecidable evidence. This is not an error state but a "
    "formal declaration that, at resolution 1/<i>D</i>, the phenomenon "
    "cannot be decided.",
    body_style
))

story.append(Paragraph(
    "The philosophical consequence: Kolmogorov's countable additivity axiom, "
    "and the entire apparatus of &sigma;-algebras and measure theory "
    "that supports it, is not a prerequisite for valid Bayesian inference. "
    "Finite additivity on a bounded arithmetic suffices. "
    "This is not a conjecture. It is a machine-verified theorem.",
    body_style
))

# --- 7. STATUS ---
story.append(Spacer(1, 12))
story.append(HRFlowable(width="60%", thickness=0.5, color=HexColor('#999999'),
                          spaceAfter=8, spaceBefore=8))

story.append(Paragraph("Formal Status", section_style))

data = [
    ["Theorem", "Status", "Dependency"],
    ["bayes_additive_bounded_error", "Qed", "pure arithmetic only"],
    ["pure_capped_error_bound", "Qed", "structural induction on Fin"],
    ["pure_floored_error_bound", "Qed", "structural induction on Fin"],
    ["fin_add_comm", "Qed", "fin_add_fz_l, fin_add_succ_l"],
    ["fin_add_assoc", "Qed", "structural induction on Fin"],
    ["bayesian_inference_without_axiom_6", "Qed", "= bayes_additive_bounded_error"],
    ["sequential_preserves_den", "Qed", "induction on evidence list"],
]

table = Table(data, colWidths=[180, 40, 200])
table.setStyle(TableStyle([
    ('FONTNAME', (0, 0), (-1, 0), 'Times-Bold'),
    ('FONTNAME', (0, 1), (-1, -1), 'Times-Roman'),
    ('FONTSIZE', (0, 0), (-1, -1), 9),
    ('LEADING', (0, 0), (-1, -1), 12),
    ('ALIGN', (1, 0), (1, -1), 'CENTER'),
    ('LINEBELOW', (0, 0), (-1, 0), 0.5, black),
    ('LINEBELOW', (0, -1), (-1, -1), 0.5, black),
    ('TOPPADDING', (0, 0), (-1, -1), 3),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
]))
story.append(table)

story.append(Spacer(1, 12))
story.append(Paragraph(
    "All proofs verified by Coq (coqc). Zero <i>Admitted</i> in the theorem chain. "
    "Source: <i>void_finite_bayes.v</i>, depending on <i>void_finite_minimal.v</i>.",
    small_style
))

# Build
doc.build(story)
print(f"PDF written to {output_path}")
